version: '3'
services:
  postgres:
    image: "postgres:9.6-alpine"
    ports:
      - "5432:5432"
    environment:
     POSTGRES_PASSWORD: devpassword
     POSTGRES_USER: bradenmacdonald
     POSTGRES_DB: bradenmacdonald
