# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=128, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('extra_js', models.TextField(blank=True)),
                ('extra_css', models.TextField(blank=True)),
                ('template', models.CharField(default='layout.html', max_length=128)),
            ],
            options={
                'verbose_name': 'Basic Page',
                'verbose_name_plural': 'Basic Pages',
                'ordering': ('path',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, upload_to='proj-thumbs')),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('source_desc', models.CharField(blank=True, max_length=128)),
                ('role', models.CharField(blank=True, max_length=128)),
                ('sortdate', models.DateField()),
                ('year', models.IntegerField(blank=True, help_text="Year, or '9999' for ongoing", null=True)),
                ('year_began', models.IntegerField(blank=True, null=True)),
                ('tags_str', models.CharField(blank=True, help_text='Tags, comma-separated', max_length=512, verbose_name='Tags')),
            ],
            options={
                'ordering': ('group__order', '-sortdate'),
            },
        ),
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('order', models.IntegerField(default=5)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='content.ProjectGroup'),
        ),
    ]
