# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 01:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('wikipedia_bio', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('original', models.TextField(blank=True, help_text='If the quotation is translated, put the original here.')),
                ('note', models.CharField(blank=True, max_length=512)),
                ('source', models.CharField(blank=True, help_text='String specifying the work in which the quote was published. Surround text with stars for italics or use HTML.', max_length=128)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('added', models.DateField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False, help_text='I personally confirmed the attribution/source.')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.Author')),
            ],
            options={
                'ordering': ('-added',),
            },
        ),
    ]
